spring:
  port: 8080
  application:
    name: continue
  datasource:
    url: jdbc:sqlite:./data/continue.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 60000ms
  thymeleaf:
    cache: false  # 开发环境关闭缓存，生产环境开启
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
      chain:
        cache: false